Test search engine
uyen3893/NopCommerceTest pull request #3
Opened 2021-03-21 09:56 UTC by uyen3893

Please review it

2021-03-21 15:07 UTC, phkhuong requested changes
Please fix as comments

2021-03-21 15:07 UTC, phkhuong commented on test/nop-page-objects/search.engine.js
> +    // get first_title() {
Please remove commented code

2021-03-21 15:07 UTC, phkhuong commented on test/specs/test_search_engine.js
> +            console.log('uyen2: ' + JSON.stringify(Search.get_title_of_product(0)))
Please remove log

2021-03-23 02:11 UTC, uyen3893 commented on test/nop-page-objects/search.engine.js
> +    // get first_title() {
Please review it

2021-03-23 02:11 UTC, uyen3893 commented on test/specs/test_search_engine.js
> +            console.log('uyen2: ' + JSON.stringify(Search.get_title_of_product(0)))
I fix it

2021-03-23 14:34 UTC, phkhuong approved these changes

2021-03-23 14:35 UTC, merged